export const EXPORT_COLUMNS = [
  { id: 'arquivo', label: 'Arquivo' },
  { id: 'linhaNF', label: 'Linha NF' },
  { id: 'dataDocumento', label: 'Data Documento' },
  { id: 'dataLancamento', label: 'Data Lançamento da NF' },
  { id: 'empresa', label: 'Empresa' },
  { id: 'descricaoEmpresa', label: 'Descrição Empresa' },
  { id: 'pedidoCompras', label: 'Pedido de Compras' },
  { id: 'itemPedidoCompras', label: 'Item do Pedido de Compras' },
  { id: 'itemDocumento', label: 'Item do Documento' },
  { id: 'numeroNF', label: 'Número da Nota Fiscal (Serviço ou Material)' },
  { id: 'notaFiscalFrete', label: 'Nota Fiscal de Frete' },
  { id: 'cfop', label: 'CFOP' },
  { id: 'naturezaOperacao', label: 'Natureza da Operação' },
  { id: 'fornecedor', label: 'Parceiro' },
  { id: 'material', label: 'Material' },
  { id: 'descricao', label: 'Descrição do Material' },
  { id: 'tipoMaterial', label: 'Tipo de Material' },
  { id: 'descricaoTipoMaterial', label: 'Descrição Tipo de Material' },
  { id: 'categoriaNF', label: 'Categoria da Nota Fiscal' },
  { id: 'origemMaterial', label: 'Origem do Material' },
  { id: 'tipoReferencia', label: 'Tipo Referência' },
  { id: 'centro', label: 'Centro' },
  { id: 'quantidade', label: 'Quantidade' },
  { id: 'precoSemFrete', label: 'Preço (Unit. s/ Frete)' },
  { id: 'precoComFrete', label: 'Preço Unitário com Frete' },
  { id: 'valorLiqSemFrete', label: 'NF Valor Líquido sem Frete' },
  { id: 'valorLiqComFrete', label: 'Valor Líquido NF com Frete' },
  { id: 'valorTotalSemFrete', label: 'Valor Total da Nota Fiscal sem Frete' },
  { id: 'valorTotalComFrete', label: 'Valor Total NF com Frete' },
  { id: 'precoEfetivo', label: 'Taxa de Câmbio / Preço Efetivo' },
  { id: 'custoPadrao', label: 'Custo SAP' },
  { id: 'variacaoPerc', label: 'Variação %' },
  { id: 'impactoFinanceiro', label: 'Impacto Financeiro' },
  { id: 'tipo', label: 'Tipo' },
  { id: 'icms', label: 'ICMS' },
  { id: 'ipi', label: 'IPI' },
  { id: 'pis', label: 'PIS' },
  { id: 'cofins', label: 'COFINS' },
  { id: 'st', label: 'ST' },
];

export const QUICK_EXPORT_COLUMNS = new Set([
  'material',
  'descricao',
  'centro',
  'cfop',
  'fornecedor',
  'dataLancamento',
  'precoEfetivo',
  'custoPadrao',
  'variacaoPerc',
  'impactoFinanceiro',
  'tipo'
]);

export const MANDATORY_CKM3_COLUMNS = [
  'Material',
  'Quantidade',
  'Centro',
  'Descrição'
];
